### ISSUE TITLE
class path problem

### ISSUE THREAD

**Issue by MaxiCode** [SSEHUB/spassMeter#1]
Hi,
i am trying to run SPASS-meter to profile the runtime of a java project. I followed your guide on dynamic instrumentation, but i gut the following error: 
```
configuration error: neither spass-meter-ia.jar nor spass-meter.jar on class path
```
I used the command: 
```
java -javaagent:spass-meter-ia-1.28.jar -jar catena.jar
```

OS: Ubuntu 17.04
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)

The spass-meter-ia-1.28.jar, spass-meter-boot-1.28.jar, and spass-meter-rt-1.28.jar jars are in the same directory.

What am i doing wrong?

Regards,
Max

**Comment by MaxiCode** [comment]
I'm not sure which which path do you mean?

I have copied the spass-meter*.jars in to the same folder where my catena.jar is. I thought it will look in the same folder where i execute my catena.jar.

Thanks for your effort and the fast answer,
Max

**Comment by eichelbe** [comment]
I meant your install path ;) Sometimes spaces or specific characters may cause unexpected problems although they should not. Just to have an impression...

**Comment by eichelbe** [comment]
Thanks for the support :) I will put this as hint into the documentation.
